---
title: "Project 3b - Data Analysis and Visualizations"
author: "Sufian"
date: "10/16/2019"
output: html_document
---



Rpub links:

http://rpubs.com/ssufian/540285



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}

# Load packages
library(rvest)
library(stringr)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(xml2)
library(httr)
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library(tidytext)
library("magrittr")



```

## R Markdown


```{r}
#read from Leticia
ltcancel<-read.csv("https://raw.githubusercontent.com/ltcancel/Project3/master/SimplyHiredJobs.csv")
colnames(ltcancel)<-c("Position", "Company","Location","Salary","URL","Job_Description")

#read from Salma
selshahawy<-read.csv("https://raw.githubusercontent.com/salma71/MSDS_2019/master/Fall2019/aquisition_management_607/project_3/jobs_detailsInfo.csv", stringsAsFactors = FALSE) 
colnames(selshahawy)<-c("Position", "Company","Location","URL","Job_Description") 

#read from Sufian
ssufian<-read.csv("https://raw.githubusercontent.com/Luz917/data607project3_ssufian_monster_jobs/master/monsterjobs.csv", stringsAsFactors = FALSE) 
colnames(ssufian)<-c("Position", "Company","Location","Salary","URL","Job_Description")  


```

## Including Plots

You can also embed plots, for example:

```{r }
twocsv<-merge(ltcancel,selshahawy,all= TRUE)

allcsv<-merge(twocsv,ssufian, all=TRUE)

head(allcsv)
```




```{r}
library("magrittr")
# REmove Salary column

clean_allcsv <- allcsv[,-c(4,6)]

head(clean_allcsv)


```


```{r}

# Removed brackets surrounding summaries

clean_allcsv <- clean_allcsv %>% mutate_each(funs(tolower), Position, Company, Location, Job_Description)

clean_allcsv1 <- str_replace_all(clean_allcsv$Job_Description, "[\r\n]" , "")
clean_allcsv1 <- str_replace_all(clean_allcsv$Job_Description, "\\." , "")
clean_allcsv1 <- str_replace_all(clean_allcsv$Job_Description, "\\*" , "")
clean_allcsv1 <- str_replace_all(clean_allcsv$Job_Description, "\\+" , "")
clean_allcsv1 <- str_replace_all(clean_allcsv$Job_Description, "\\\\" , "")
clean_allcsv1 <- str_replace_all(clean_allcsv$Job_Description, "\\)" , "")
clean_allcsv1 <- str_replace_all(clean_allcsv$Job_Description, "\\(" , "")
clean_allcsv1 <- str_replace_all(clean_allcsv$Job_Description, "[[:punct:]]+", "")
clean_allcsv1 <- str_replace_all(clean_allcsv$Job_Description, "[\n]" , "")


head(clean_allcsv1 )
              
clean_allcsv2 <- clean_allcsv[,-c(4)] # this is for sentinment later


clean_allcsv2$Job_Description <- clean_allcsv1 
  
```



```{r}
#tfidf <- clean_allcsv1
tfidf <- clean_allcsv2$Job_Description 

# Control list to be used for all corpuses
control_list <- list(removePunctuation = TRUE, stopwords = TRUE, tolower = TRUE,
                     weighting = weightTfIdf)

```

```{r}
# TF-IDF Based on the 3 job postings

corpus.all <- VCorpus(VectorSource(tfidf))
tdm.all <- TermDocumentMatrix(corpus.all, control = control_list)
inspect(tdm.all)
# Remove outliers consisting of very rare terms
tdm.40 <- removeSparseTerms(tdm.all, sparse = 0.40)
inspect(tdm.40)
# Sum rows for total & make dataframe
df_all <- tidy(sort(rowSums(as.matrix(tdm.40))))
colnames(df_all) <- c("words", "count")
View(df_all)


```




```{r}


# Graph
ggplot(tail(df_all, 25), aes(reorder(words, count), count)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(title = "TF-IDF of 3 Job Postings",
       x = "Words", y = "Frequency") +
  coord_flip()

```
```{r}
docs <- Corpus(VectorSource(clean_allcsv2$Job_Description))
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs  , toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
docs <- tm_map(docs, stemDocument)

inspect(docs)
dtmw <- TermDocumentMatrix(docs )
m <- as.matrix(dtmw)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)

```

### Generate the Word cloud

The important key skill sets can be illustrated as a word cloud as follow :


```{r}
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```

### Explore frequent terms and their associations


```{r}

findFreqTerms(dtmw, lowfreq = 4)


findAssocs(dtmw, terms = "data scientist", corlimit = 0.3)

```


### Top 10 most frequent words in the job descriptions of the 3 job sites

```{r}
barplot(d[1:10,]$freq, las = 2, names.arg = d[1:10,]$word,
        col ="lightblue", main ="Most frequent words",
        ylab = "Word frequencies")
```
```{r}

# For display purpose, we also need the \\b removed from the keyword set
KEYWORDS_DISPLAY <- c('Hadoop','Python','SQL', 'NoSQL','R', 'Spark', 'SAS', 'Excel', 'AWS', 'Azure', 'Java', 'Tableau')

# Create running total dataframe
running <- data.frame(skill = KEYWORDS_DISPLAY, count = rep(0, length(KEYWORDS_DISPLAY)))



```

### Sentiment Analysis


```{r}

toolskills <- clean_allcsv2 %>%
    mutate(R = grepl("\\bR\\b,", Job_Description, ignore.case=TRUE)) %>%
    mutate(python = grepl("Python", Job_Description, ignore.case=TRUE)) %>%
    mutate(SQL = grepl("SQL", Job_Description, ignore.case=TRUE)) %>%
    mutate(hadoop = grepl("hadoop", Job_Description, ignore.case=TRUE)) %>%
    mutate(perl = grepl("perl", Job_Description, ignore.case=TRUE)) %>%
    mutate(matplotlib = grepl("matplotlib", Job_Description, ignore.case=TRUE)) %>%
    mutate(Cplusplus = grepl("C++", Job_Description, fixed=TRUE)) %>%
    mutate(VB = grepl("VB", Job_Description, ignore.case=TRUE)) %>%
    mutate(java = grepl("java\\b", Job_Description, ignore.case=TRUE)) %>%
    mutate(scala = grepl("scala", Job_Description, ignore.case=TRUE)) %>%
    mutate(tensorflow = grepl("tensorflow",Job_Description, ignore.case=TRUE)) %>%
    mutate(javascript = grepl("javascript", Job_Description, ignore.case=TRUE)) %>%
    mutate(spark = grepl("spark", Job_Description, ignore.case=TRUE)) %>%
   # mutate(spark = grepl("Hadoop", Job_Description, ignore.case=TRUE)) %>%  
    # mutate(spark = grepl("nosql", Job_Description, ignore.case=TRUE)) %>%  
     # mutate(spark = grepl("spark", Job_Description, ignore.case=TRUE)) %>%  
     # mutate(spark = grepl("sas", Job_Description, ignore.case=TRUE)) %>%  
     # mutate(spark = grepl("excel", Job_Description, ignore.case=TRUE)) %>%  
     # mutate(spark = grepl("aws", Job_Description, ignore.case=TRUE)) %>%  
      #mutate(spark = grepl("azure", Job_Description, ignore.case=TRUE)) %>%  
      mutate(spark = grepl("java", Job_Description, ignore.case=TRUE)) %>%   
      #mutate(spark = grepl("tableau", Job_Description, ignore.case=TRUE)) %>% 
  
  
select(Position, Company, R, python, SQL, hadoop, perl, matplotlib, Cplusplus, VB, java, scala, tensorflow, javascript,spark,java)

```

```{r}
toolskills2 <- toolskills %>% select(-(1:2)) %>% summarise_all(sum) %>% gather(variable,value) %>% arrange(desc(value))
```

### Visualized the most in-demand tool sKills:

```{r}
ggplot(toolskills2,aes(x=reorder(variable, value), y=value)) + geom_bar(stat='identity',fill="green") + xlab('') + ylab('Frequency') + labs(title='Tool Skills') + coord_flip() + theme_minimal()
```

